# Latent Dirichlet Allocation

## Data

In [25]:
import pandas as pd

In [26]:
npr = pd.read_csv('npr.csv')

In [27]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

## Preprocessing

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [30]:
dtm = cv.fit_transform(npr['Article'])

In [31]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [32]:
from sklearn.decomposition import LatentDirichletAllocation

In [33]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [34]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

C:\Users\a\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py:536: DeprecationWarning: The default value for 'learning_method' will be changed from 'online' to 'batch' in the release 0.20. This warning was introduced in 0.18.
  DeprecationWarning)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7, learning_method=None,
             learning_offset=10.0, max_doc_update_iter=100, max_iter=10,
             mean_change_tol=0.001, n_components=7, n_jobs=1,
             n_topics=None, perp_tol=0.1, random_state=42,
             topic_word_prior=None, total_samples=1000000.0, verbose=0)

## Showing Stored Words

In [35]:
len(cv.get_feature_names())

54777

In [36]:
import random

In [37]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

portela
considerate
towed
supersedes
doctrines
dissipation
bureaucrat
rochelle
xp
digital


In [38]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

wiped
developed
postdoctoral
compensatory
pinged
hopping
falsehood
mehldau
dambara
lilies


### Showing Top Words Per Topic

In [39]:
len(LDA.components_)

7

In [40]:
LDA.components_

array([[2.55030234e+01, 1.18160521e+03, 1.42857161e-01, ...,
        1.42942888e-01, 1.42865635e-01, 1.42994709e-01],
       [1.75938770e+01, 7.79163845e+00, 1.42871959e-01, ...,
        1.42857152e-01, 1.43057304e-01, 1.42990129e-01],
       [5.56830532e+00, 7.61579261e+02, 1.42857370e-01, ...,
        4.84616992e+00, 2.46543716e+00, 1.42942152e-01],
       ...,
       [1.43329722e-01, 6.12135291e+02, 1.42857193e-01, ...,
        1.42868589e-01, 1.42859011e-01, 1.42897792e-01],
       [3.89096469e+01, 1.97272208e+01, 4.00585507e+00, ...,
        1.43174190e-01, 1.45396934e-01, 2.17293923e+00],
       [5.82136826e+00, 1.76095158e+03, 1.43163938e-01, ...,
        1.42994603e-01, 1.43326983e-01, 1.42965349e-01]])

In [41]:
len(LDA.components_[0])

54777

In [42]:
single_topic = LDA.components_[0]

In [43]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([49163, 21347, 20789, ..., 37374, 42993, 42561], dtype=int64)

In [44]:
# Word least representative of this topic
single_topic[18302]

0.14288722316053026

In [45]:
# Word most representative of this topic
single_topic[42993]

5308.193870788635

In [46]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([ 9511, 49613, 53019, 11657, 21228, 40955, 36283, 37374, 42993,
       42561], dtype=int64)

In [47]:
top_word_indices = single_topic.argsort()[-10:]

In [48]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

city
told
war
country
government
reports
people
police
says
said


In [49]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['state', 'attack', 'killed', 'according', 'military', 'city', 'told', 'war', 'country', 'government', 'reports', 'people', 'police', 'says', 'said']


THE TOP 15 WORDS FOR TOPIC #1
['russian', 'npr', 'fbi', 'did', 'clinton', 'told', 'media', 'white', 'campaign', 'russia', 'house', 'news', 'president', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['world', 'year', 'make', 'day', 'home', 'time', 'city', 'new', 'years', 'just', 'people', 'water', 'like', 'food', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['women', 'don', 'just', 'research', 'like', 'university', 'children', 'percent', 'care', 'study', 'students', 'school', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['vote', 'court', 'new', 'percent', 'republican', 'law', 'campaign', 'obama', 'states', 'people', 'president', 'clinton', 'state', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['ve', 'going', 'years', 'don', 'life', 'new', 'really', 'way', 'says', 'know', 'think', 'time', 'pe

### Attaching Discovered Topic Labels to Original Articles

In [50]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [51]:
dtm.shape

(11992, 54777)

In [52]:
len(npr)

11992

In [53]:
topic_results = LDA.transform(dtm)

In [54]:
topic_results.shape

(11992, 7)

In [55]:
topic_results[0]

array([7.31632607e-02, 6.75553233e-01, 6.25535235e-03, 2.25570582e-04,
       2.21208569e-01, 2.25552570e-04, 2.33684623e-02])

In [56]:
topic_results[0].round(2)

array([0.07, 0.68, 0.01, 0.  , 0.22, 0.  , 0.02])

In [57]:
topic_results[0].argmax()

1

### Combining with Original Data

In [58]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [59]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 4], dtype=int64)

In [60]:
npr['Topic'] = topic_results.argmax(axis=1)

In [61]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      5
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      2
9  Eighteen years ago, on New Year’s Eve, David F...      2